# === PATHS ===
data_paths:
  raw: data/raw/
  processed: data/processed/
  model_output: models/
  visualizations: outputs/figures/

# === MODEL SETTINGS ===
model:
  name: "ARIMA"
  forecast_horizon: 30    # Nombre de jours à prédire
  confidence_level: 0.95

# === API / DATA ===
yfinance:
  tickers: ["^VIX", "^GSPC"]
  start_date: "2004-01-01"
  end_date: "2024-12-31"
  interval: "1d"

# === VISUALIZATION ===
plot:
  theme: "plotly_dark"
  show_confidence_interval: true